### ISSUE TITLE
Support "semver resolution" in `deps.ts`

### ISSUE THREAD

**Issue by binyamin** [oakserver/acorn#3]
Deno's standard library (std) updates very often, like every week, so I personally try to only update when the minor version hits a multiple of 10 (`0.210.x` to `0.220.x`).

Semver makes dependency-resolution much easier. The impact is twofold: (1) users don't need to download 2+ versions of the same module, and (2) maintainers don't need to update the code/package as often.

See also https://jsr.io/docs/using-packages#semver-resolution

**Example**
```diff
- export { assert } from "jsr:@std/assert@0.218/assert";
- export { SecureCookieMap } from "jsr:@oak/commons@0.7/cookie_map";
+ export { assert } from "jsr:@std/assert@^0.218/assert";
+ export { SecureCookieMap } from "jsr:@oak/commons@^0.7/cookie_map";
```

**Comment by kitsonk** [comment]
Deno has regularly been making breaking changes to the std library on minor releases (demonstrated by `@oak/commons` even existing as it basically contains stuff that was once in std but now isn't). Putting semver on that is quite dangerous up until std 1 is released.

So thanks for the suggestion, but not at this time.
